### ISSUE TITLE
Release as v1.0.0

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli-chai#18]
to reduce the friction of things like https://github.com/ember-cli/ember-cli-mocha/issues/154 we should probably release a `v1.0.0` version rather sooner than later.

**Comment by Dhaulagiri** [comment]
That seems reasonable.  It seems unlikely there will be a lot of backwards incompatible churn here.

**Comment by Turbo87** [comment]
actually I just remembered that Chai v4 will be released soon, so maybe we should wait for that before declaring v1.0.0?

**Comment by Turbo87** [comment]
maybe @keithamus can tell us if it will be worth waiting and a rough time schedule?

**Comment by keithamus** [comment]
I would imagine we'll release 4.0 before the end of the year, we've had a few weeks with no real issues. There's a good chance it could land as a christmas gift for all.

However plugins will need to catch up - that could take longer and could be a point of friction for users. Up to you on that one.

**Comment by Turbo87** [comment]
@keithamus thanks for the feedback. I guess we'll go with v3.x then and update once the dust has settled.
