### ISSUE TITLE
Support for testdouble-chai

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli-chai#19]
similar to #14

see https://github.com/BaseCase/testdouble-chai

this would deprecate https://github.com/alexlafroscia/ember-cli-testdouble-chai

also note that this might conflict with `sinon-chai`, so we should make sure that only one of them can be used at the same time.

**Comment by alexlafroscia** [comment]
I was actually planning to make an issue here to suggest just this. I'll take a look at making this work and deprecating my add-on.

**Comment by alexlafroscia** [comment]
RE: only using `sinon-chai` or `testdouble-chai`:

It seems like the approach with all of these addons is to enable them by default. What if the approach instead checked the application for the dependency being installed, and then automatically enables it only if found?  It seems reasonable to be able to say, for example, check for `testdouble-chai` in `app.bowerDirectory` and also attempt to `require.resolve`, then only import/enable it if it's there. A little more work on the add-on's end, but that would limit the number of dependencies here and make an easy way for avoiding conflicts, simply by having the user of `ember-cli-chai` not install both.

**Comment by alexlafroscia** [comment]
@Turbo87 Do you have any suggestions on how we might ensure that there aren't conflicts between the `testdouble-chai` and `sinon-chai`? Is there a good method for running tests where only one or the other is enabled?

**Comment by alexlafroscia** [comment]
Actually, I see that the jQuery and DOM plugins are never both enabled, I'll use that as a reference for how to handle both being present, preferring `sinon` since it's a more popular library.

**Comment by Turbo87** [comment]
> Actually, I see that the jQuery and DOM plugins are never both enabled, I'll use that as a reference for how to handle both being present, preferring sinon since it's a more popular library.

that is exactly what I would've suggested 👍
