### ISSUE TITLE
Support dirty-chai

### ISSUE THREAD

**Issue by Vassi** [ember-cli/ember-cli-chai#22]
Not sure how feasible this one is, considering it has to run before any other plugins, but it would be nice to support [dirty-chai](https://github.com/prodatakey/dirty-chai).

**Comment by Turbo87** [comment]
@Vassi while I'm not a huge fan of dirty-chai I would most likely accept pull requests that implement optional support for dirty-chai. I don't see any immediate blockers right now for implementing such a PR, but I won't put any work in this myself.
