### ISSUE TITLE
Allow configuring additional plugins in package.json?

### ISSUE THREAD

**Issue by job13er** [ember-cli/ember-cli-chai#23]
I was considering trying to add a feature here that would allow `ember-cli-chai` to read in metadata about additional chai plugins from a section of `package.json`, formatted similarly to [the existing plugin definitions](https://github.com/ember-cli/ember-cli-chai/blob/master/index.js#L13-L17), at least for the simpler cases where only `name`, `constraint`, and `path` are needed. 

This would allow for consumers to specify their own set of chai plugins they want to use, and let `ember-cli-chai` load them all automatically. It could also potentially negate the need for #10, #11 and #12 

Before I got started on that change, I wanted to check and see if it was something you'd be interested in merging. 

Please let me know what you think.

Thanks.

**Comment by Turbo87** [comment]
@ember-cli/core I'd like some opinions on this. I'm not sure about it...

**Comment by job13er** [comment]
If the `package.json` isn't a good place for it, I'd be willing to try to put such a config somewhere else, like `config/chai.js` maybe.

**Comment by nathanhammond** [comment]
@job13er This has trolled us a ton in the past:

- We use Broccoli to create "views" on the file system.
- When we do that we lose context of where the asset was originally stored.
- Any path-relative config file is now somewhere between incredibly difficult to use or just wrong.

To this point we've also resisted defining our own configuration system and instead opted to defer to the built-in approaches for these tools. I'm unfamiliar with Chai, but if it is not a default, I'm opposed on principle as I feel like that should belong upstream.

**Comment by job13er** [comment]
No worries. Understood. I'll write something just for us then. Just thought I'd check if you'd be interested.

**Comment by nathanhammond** [comment]
If you can do it as an addon that will make it more resilient, and then we can explore the space as a community. If it turns out to be awesome we may yet want it!

Thanks for your thoughts in this!
