### ISSUE TITLE
Using with QUnit?

### ISSUE THREAD

**Issue by lolmaus** [ember-cli/ember-cli-chai#3]
Is it possible to use `ember-cli-chai` with QUnit?

If yes, it is confusing how it is supposed to be used. QUnit provides its own `assert` function. Should i not use the QUnit's one? Should i use both? Does Chai's `assert` provide QUnit's features like `assert.expect()`, `assert.async()`?

Please expand the readme with answers to those questions and some example code.

**Comment by mattmcmanus** [comment]
+1

**Comment by jonathanKingston** [comment]
Due to naming issues with QUnit and Chai, you may need to use *as* in the import statement.

This seems to work for all the use cases you have mentioned.

```
import { moduleForModel, test } from 'ember-qunit';
import { assert as cassert } from 'chai';

moduleForModel('thing', 'Unit | Model | thing', {
  // Specify the other units that are required for this test.
  needs: []
});

test('it exists', function(assert) {
  var model = this.subject();
  // var store = this.store();
  cassert.ok(!!model);
  assert.ok(!!model);
});
```

Sorry for the delay with this.

**Comment by jonathanKingston** [comment]
@mattmcmanus or @lolmaus let me know if you have issues and I can then update the documentation.

**Comment by lolmaus** [comment]
Hey @jonathanKingston, I've tried it and found a problem: Chai correctly reports failed assertions to QUnit (though the output is far from being expressive), but it does not report successful assertions. They do not appear on the list and do not increment the assertion counter.

Even worse, if you only have Chai assertions in a test block, QUnit would report:

> Expected at least one assertion, but none were run - call expect(0) to accept zero assertions.

**Comment by justin-hackin** [comment]
I suggest a big warning at the top of the README to inform others that this is not compatible with standard ember tests.   No qunit compatibility = a bunch of wasted time in vain hopes of incorporating chai yummyness... best of wishes on making this more useful :)

**Comment by lolmaus** [comment]
So I implemented this instead: https://github.com/lolmaus/ember-cli-custom-assertions-collection
