### ISSUE TITLE
could not find module `chai` (new module unification)

### ISSUE THREAD

**Issue by efx** [ember-cli/ember-cli-chai#37]
I started migrating our app using https://github.com/rwjblue/ember-module-migrator/ and the https://github.com/emberjs/ember-module-unification-blueprint. The app builds successfully, but fails to load from the following error:
<img width="902" alt="screen shot 2017-09-25 at 8 37 27 am" src="https://user-images.githubusercontent.com/472721/30808593-c6232d28-a1cc-11e7-800c-a84704bada13.png">
The import lines in that test file are:
```js
import { expect } from 'chai';
import { describe, it, beforeEach } from 'mocha';
import Ember from 'ember';
import { initialize } from "web-server/src/init/initializers/application/initializer";
import destroyApp from 'web-server/tests/helpers/destroy-app';
import sinon from 'npm:sinon';
```

``` 
$ npm ls chai
└─┬ ember-cli-chai@0.4.2
  └── chai@3.5.0 
```

Our project's vendor.js does not appear to have chai loaded.  This is a private repo but I am happy to test it / move this issue to a more relevant location.

**Comment by Turbo87** [comment]
@rwjblue @mixonic any ideas?

**Comment by mixonic** [comment]
@efx I'm surprised moving to module unification would break this kind of import. Scanning the code `chai` [should be in the vendor tree](https://github.com/ember-cli/ember-cli-chai/blob/master/index.js#L130). If it was exposing the library via the `app/` directory I would expect issues, but on the surface this looks fine. 

I think this simply needs to be debugged. I don't see anything in that `index.js` that seems coupled to the `app/` tree.

**Comment by efx** [comment]
I was mistaken about not being included in the app. Chai does appear in `dist/assets/test-support.js`. I was thinking it should appear in `vendor.js`. I'll look at the require there;

**Comment by efx** [comment]
Turns out running`ember build` builds the app with module resolutions for tests. e.g. `ember-test` and all our application test files.  This seems incorrect. It also seems like a resolver issue, not an ember-cli-chai. Open to direction on where to move this, ideas about useful further debugging.

**Comment by efx** [comment]
Removing the test files from`src/initializers` tree prevents this specific error from appearing. So it seems the `-test` files are not being excluded properly with ember build. This may relate to https://github.com/ember-cli/ember-load-initializers/issues/42.

**Comment by efx** [comment]
I'm closing this because the underlying issue appears caused by the initializer loading.
