### ISSUE TITLE
Do you need help?

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli-chai#5]
Hello @jonathanKingston! 👋 

It seems that this package could use a few more maintainers and I would like to offer my help. We could possibly make this an official Ember CLI project, like we did with `ember-cli-eslint` too.

In the current state `ember-cli-mocha` already includes Chai, but as you can see in https://github.com/ember-cli/ember-cli-mocha/issues/132 we would like to extract that into a separate project, just like the project that you have here. My plan would be to merge those two projects and make this one a subdependency of `ember-cli-mocha`.

Please let me know what you think about it!

**Comment by jonathanKingston** [comment]
Sounds great to me! As you can probably tell I don't do any ember at all
nor do I think Mozilla so it's hard to push for work time on it also.

I shall add you to the admin when I get home. The direction is the was I
wished it to go anyway so that is nice!

**Comment by Turbo87** [comment]
awesome, thanks for the quick reply!

**Comment by Turbo87** [comment]
@jonathanKingston could you `npm owner add turbo87` too?

**Comment by jonathanKingston** [comment]
Done :)

**Comment by Turbo87** [comment]
@jonathanKingston thanks! from what you wrote earlier I assume you are okay with me moving this project into the `ember-cli` GitHub organization?

**Comment by jonathanKingston** [comment]
Yup totally, I wasn't admin of the ember-cli group or else I would have
done that myself.

**Comment by Turbo87** [comment]
@jonathanKingston it seems that only the repo owner is able to move projects. I've temporarily granted you owner permissions on the `ember-cli` org. Please let me know if this works.

**Comment by jonathanKingston** [comment]
Done :) thanks!
